controller_manager:
  ros__parameters:
    update_rate: 1000 

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    two_wheel_control:
      type: two_wheel_control/TwoWheelIDController 
      


two_wheel_control:
  ros__parameters:
    body_I_diag:
      - 1.9
      - 3.3
      - 1.9
    wheel_I_diag:
      - 0.002
      - 0.001
      - 0.001
    body_mass: 20.0
    wheel_mass: 0.1
    body_height: 0.5
    wheel_radius: 0.2
    wheel_distance: 0.4
    Kp:
      - 1.0
      - 200.0
      - 1.0
    Kd:
      - 1.0
      - 100.0
      - 1.0

    feedback:
      - velocity
      - position

    
