controller_manager:
  ros__parameters:
    update_rate: 100 

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    two_wheel_control:
      type: two_wheel_control/TwoWheelIDController 
      


two_wheel_control:
  ros__parameters:
    body_I_diag:
      - 1.9
      - 3.3
      - 1.9
    wheel_I_diag:
      - 0.002
      - 0.001
      - 0.001
    body_mass: 20.0
    wheel_mass: 0.1
    body_height: 0.5
    wheel_radius: 0.1
    wheel_distance: 0.4

    max_angle: 0.4

    # GOOD FOR 100 Hz
    # Kp:
    #   - 0.01
    #   - 50.0
    #   - 55.0
    # Kd:
    #   - 0.013
    #   - 30.0
    #   - 15.0

    Kp:
      - 0.10
      - 55.0
      - 50.0
    Kd:
      - 0.07
      - 30.0
      - 15.0

    feedback:
      - velocity
      - position

    tuning: true

    
