controller_manager:
  ros__parameters:
    update_rate: 1000 

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    two_wheel_control:
      type: two_wheel_control/TwoWheelIDController 

    use_sim_time: true
      


two_wheel_control:
  ros__parameters:
    update_rate: 1000.0

    body_I_diag:
      - 1.9
      - 3.3
      - 1.9
    wheel_I_diag:
      - 0.002
      - 0.001
      - 0.001
    body_mass: 20.0
    wheel_mass: 0.1
    body_height: 0.5
    wheel_radius: 0.1
    wheel_distance: 0.41

    max_angle: 0.6

    # Velocity Control 1000Hz
    P:
      - 0.0
      - 50.0
      - 100.0
      - 0.02
      - 5.0
      - 50.0
    I:
      - 0.0
      - 100.0
      - 10.0
      - 0.0
      - 0.0
      - 0.0
    D:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    max_I:
      - 100.0
      - 100.0
      - 100.0
      - 100.0
      - 100.0
      - 100.0

    # VELOCITY CONTROL 100 Hz
    # P:
    #   - 0.0
    #   - 200.0
    #   - 100.0
    #   - 0.015
    #   - 10.0
    #   - 50.0
    # I:
    #   - 0.0
    #   - 100.0
    #   - 10.0
    #   - 0.0
    #   - 0.0
    #   - 0.0
    # D:
    #   - 0.0
    #   - 0.0
    #   - 0.0
    #   - 0.0
    #   - 0.0
    #   - 0.0
    # max_I:
    #   - 100.0
    #   - 100.0
    #   - 100.0
    #   - 100.0
    #   - 100.0
    #   - 100.0

    # POSITION CONTROL 100Hz
    # P:
    #   - 0.01
    #   - 200.0
    #   - 100.0
    #   - 0.005
    #   - 10.0
    #   - 50.0
    # I:
    #   - 0.005
    #   - 100.0
    #   - 1.0
    #   - 0.0
    #   - 10.0
    #   - 0.0
    # D:
    #   - 0.0
    #   - 0.1
    #   - 0.0
    #   - 0.0
    #   - 0.1
    #   - 0.0
    # max_I:
    #   - 100.0
    #   - 100.0
    #   - 100.0
    #   - 100.0
    #   - 100.0
    #   - 100.0


    # GOOD FOR 100 Hz
    # Kp:
    #   - 0.01
    #   - 50.0
    #   - 55.0
    # Kd:
    #   - 0.013
    #   - 30.0
    #   - 15.0
    # OLDER VERSION, DEPRECATED
    # Kp:
    #   - 0.10
    #   - 55.0
    #   - 50.0
    # Kd:
    #   - 0.07
    #   - 30.0
    #   - 15.0

    tuning: false

    avg_size: 20

    
