function dYdt = Pendulum_sys(t,Y,m,g,l)
%Pendulum_sys
%    dYdt = Pendulum_sys(T,Y,M,G,L)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    12-Jul-2022 15:48:05

dYdt = [Y(2);-(g.*sin(Y(1)))./l];
